name: theme_configurator
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  gluestack_ui:
    path: ./gluestack-ui-flutter
  device_preview: ^1.1.0
  flutter_bloc: ^8.1.4
  flutter_colorpicker: ^1.0.3
  flutter_image_stack: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
